# Generated by Django 4.1.7 on 2023-03-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_activelistings_comments_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveListings',
            new_name='ActiveListing',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
