# Generated by Django 4.1.7 on 2023-03-22 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_activelistings_activelisting_rename_bids_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelisting',
            name='category',
            field=models.CharField(default='Electronics', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activelisting',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='listing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
