# Generated by Django 4.1.7 on 2023-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_alter_activelisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelisting',
            name='active',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
