# Generated by Django 4.1.7 on 2023-04-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_activelisting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='description',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='listing_title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
