# Generated by Django 4.1.7 on 2023-04-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_watchlist_listings_watchlist_listings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listings')},
        ),
    ]
